name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --target=api_builder --tag i_api_builder:$(date +%s)
  build-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --target=app_builder --tag i_app_builder:$(date +%s)
  build-deploy:
    runs-on: ubuntu-latest
    needs: [build-api, build-app]
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --target=fullstack_local_deploy --tag i_fullstack_local_deploy:$(date +%s)
